# Generated by Django 4.2.1 on 2023-06-14 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petsapp', '0004_author_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
