# Generated by Django 4.2.1 on 2023-09-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='state',
            field=models.CharField(choices=[('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('Goa', 'Goa'), ('GJ', 'Gujurat'), ('RJ', 'Rajasthan'), ('MH', 'Maharashtra'), ('UP', 'Uttar Pradesh')], default='MH', max_length=100),
        ),
    ]
